## YAML Template.

stages:
    - deploy

test:
    stage: deploy
    script:
        - echo "Deploy intranet"
        - env

    tags:
        - test

deploy:
    stage: deploy
    script:
        - echo "Deploy intranet"
        - env
        - cp -r * $PROJECT_SRCDIR
        - cp -r htdocs/* $PROJECT_HTTPDIR
#    environment:
#        name: production
#        url: http://intra.epitanime.com/
#    only:
#        - master
    tags:
        - test
