## YAML Template.

stages:
    - deploy

deploy:
    stage: deploy
    script:
        - rm -rf $PROJECT_SRCDIR/*
        - cp -r * $PROJECT_SRCDIR
        - cp -r htdocs/* $PROJECT_HTTPDIR
    environment:
        name: production
        url: http://intra.epitanime.com/
    only:
        - master
    tags:
        - prod
