name: cms
label: Intranet
fields:
    wait_logout:
        type: int
        label: Temps (mins) avant déconnexion
        default: 1
    max_logaudit:
        type: int
        label: Nombre de tentatives de connexion maximal par heure
        default: 9
    rgpd_days:
        type: int
        label: Nombre de jours depuis la dernière connexion d'un utilisateur avant suppression des données personnelles.
        default: 730
